"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ['page.ui', 'button.ui', 'extra_label.ui', 'loading.gif']
OPTIONS = {'iconfile': '/Users/dom/Desktop/python-app/logo.jpg'} #la cartella deve essere quella effettiva dove si trova il file

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'PyQt5']
)
